<a href="https://colab.research.google.com/github/pranjul-05/Tensors_begining/blob/main/Tensors_begining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



In [ ]:
a = np.array(4)

In [ ]:
a

array(4)

a.ndim


In [ ]:
arr = np.array([1,2,3,4,5]) # 1D Tensor/ 1D Array

In [ ]:
arra = np.array(4)

array([1, 2, 3, 4, 5])

In [ ]:
arr.ndim

1

In [ ]:
import numpy as np

In [ ]:
# 2D Tensor/ 2D Array
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mat.ndim

2

In [ ]:
import numpy as np
matr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
matr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/placement.csv') # Function To read CSV files and pandas function is stored in df

In [ ]:
df.head() # when we have to take a overview of pandas Dataframe

,Unnamed: 0,cgpa,iq,placement
0,0,6.8,123.0,1
1,1,5.9,106.0,0
2,2,5.3,121.0,0
3,3,7.4,132.0,1
4,4,5.8,142.0,0


In [ ]:
df.shape

(100, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  100 non-null    int64  
 1   cgpa        100 non-null    float64
 2   iq          100 non-null    float64
 3   placement   100 non-null    int64  
dtypes: float64(2), int64(2)
memory usage: 3.3 KB
